PluginPrefix: '&a[NekoC]'

NekoChat: true

MeatOnly: true

Catnip: true

Pat: true
Lovebite: true
Nightvision: true
Purr: true
Earscratch: true
Attention: true
Hiss: true
Scratch: true

GlobalCommandMessages: false
InedibleForCat:
  - APPLE
  - MUSHROOM_STEW
  - BREAD
  - GOLDEN_APPLE
  - ENCHANTED_GOLDEN_APPLE
  - MELON_SLICE
  - DRIED_KELP
  - CARROT
  - POTATO
  - BAKED_POTATO
  - POISONOUS_POTATO
  - PUMPKIN_PIE
  - BEETROOT
  - BEETROOT_SOUP
  - SWEET_BERRIES
  - CARROT_ITEM
  - POTATO_ITEM
  - MELON
ConfigVersion: 1.0