
PluginPrefix: "&a[NekoC]"

NekoChat: true

MeatOnly: true

Pet: true
Lovebite: true
Nightvision: true
Purr: true
Earscratch: true
Attention: true
Hiss: true
Scratch: true

GlobalCommandMessages: false

UnedibleForCat:
  - APPLE
  - MUSHROOM_STEW
  - BREAD
  - GOLDEN_APPLE
  - ENCHANTED_GOLDEN_APPLE
  - MELON_SLICE
  - DRIED_KELP
  - CARROT
  - POTATO
  - BAKED_POTATO
  - POISONOUS_POTATO
  - PUMPKIN_PIE
  - BEETROOT
  - BEETROOT_SOUP
  - SWEET_BERRIES
  - CARROT_ITEM #Theese three are only here for lower version compatibility reasons.
  - POTATO_ITEM
  - MELON

Nekos:
  - PlayerUserName