PluginPrefix: '&a[NekoC]'

Permission based Neko Checking: false

NekoChat: true

MeatOnly: true

Catnip: true

Pat: true
Lovebite: true
Nightvision: true
Jumpboost: true
Purr: true
Earscratch: true
Attention: true
Hiss: true
Scratch: true
SwiftSneak: true
Claws: true

SwiftSneak Level: 3

Claw Poison Level: 1
Claw Poison Duration: 10
Claw Poison Chance: 25
Claw Damage: 1
Claw Damage Additive: false

GlobalCommandMessages: false
InedibleForCat:
  - APPLE
  - MUSHROOM_STEW
  - BREAD
  - GOLDEN_APPLE
  - ENCHANTED_GOLDEN_APPLE
  - MELON_SLICE
  - DRIED_KELP
  - CARROT
  - POTATO
  - BAKED_POTATO
  - POISONOUS_POTATO
  - PUMPKIN_PIE
  - BEETROOT
  - BEETROOT_SOUP
  - SWEET_BERRIES
  - CARROT_ITEM
  - POTATO_ITEM
  - MELON
ConfigVersion: 1.5